name = "JokerJailBreak"
uuid = "58f162c1-cbb9-45ca-87ec-ee33e09b9a4e"
version = "0.1.0"
authors = ["itsdfish"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
Combinatorics = "1.0.0"
Random = "1"
SafeTestsets = "0.0.1, 0.1"
StatsBase = "0.33.0, 0.34"
julia = "1"

[extras]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StatsBase"]
